### PR TITLE
Added rendering support for shrubs

### PR DESCRIPTION
**Pull request by Dnawrkshp**
Tested and working on RC4 and RC3.

Shrubs render with their textures in wrench. The UV mapping appears to be off. There is data within each shrub that contains information like tiling and rotation. Maybe more can be looked into how that affects texture mapping.

RC4 Maraxus:
image

RC4 Shaar:
image

RC3 level20:
image

RC3 level14:
image

### CODE REVIEW

**Comment by chaoticgd** [comment]
I'm getting a build error with gcc:

> /home/thomas/projects/wrench-editor/src/formats/level_impl.cpp:196:76: error: cannot bind packed field ‘entry.level_shrub_model_entry::offset_in_asset_wad’ to ‘unsigned int&’
  196 |   shrub_model& model = shrub_models.emplace_back(&(*_asset_segment), entry.offset_in_asset_wad, 0);

I've had this error before, it's a quirk with packed structs in C++. To fix it just store entry.offset_in_asset_wad in a local variable before passing it to the function. I think it happens because you can't take unaligned references to things.

**Comment by Dnawrkshp** [comment]
Alright I changed it. Let me know if it compiles for you now.

**Comment by chaoticgd** [comment]
It compiles but fails to link. Looks like you also forgot to add the modified CMakeLists.txt file to source control.

**Comment by chaoticgd** [comment]
All good now.

**Pull request merged**
